cong_report/urls.py
from django.contrib import admin
from django.urls import path
from frontend.views import PublisherAutocomplete, get_report

from frontend.views import cong_submission


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", cong_submission),
    path("<str:congregation_code>/", cong_submission),
    path("report/<int:group_id>/", get_report),
    path("report/<int:group_id>/<int:year>/<int:month>", get_report),
    path(
        r"^publisher-autocomplete/$",
        PublisherAutocomplete.as_view(),
        name="publisher-autocomplete",
    ),
]

admin.site.site_header = "Field Service Group Admin"

frontend/models.py
from django.db import models

# Create your models here.

ministry/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Report(models.Model):
    publisher = models.ForeignKey("congregation.Publisher", on_delete=models.CASCADE)
    hours = models.IntegerField(default=0)
    return_visits = models.IntegerField(default=0)
    bible_studies = models.IntegerField(default=0)
    placements = models.IntegerField(default=0)
    videos = models.IntegerField(default=0)
    remarks = models.TextField(max_length=5000, null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    last_change_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.creation_date.month}/{self.creation_date.year} - {self.publisher.name}"

frontend/forms.py
from django import forms

from ministry.models import Report
from dal import autocomplete


class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)


class ReportForm(forms.ModelForm):
    remarks = forms.CharField(required=False, widget=forms.Textarea(attrs={"rows": 4}))
    hours = forms.IntegerField(required=False, initial="")
    return_visits = forms.IntegerField(required=False, initial="")
    bible_studies = forms.IntegerField(required=False, initial="")
    placements = forms.IntegerField(required=False, initial="")
    videos = forms.IntegerField(required=False, initial="")

    class Meta:
        model = Report
        fields = [
            "publisher",
            "hours",
            "return_visits",
            "bible_studies",
            "placements",
            "videos",
            "remarks",
        ]
        labels = {
            "publisher": "Publisher",
        }
        widgets = {
            "publisher": autocomplete.ModelSelect2(
                url="publisher-autocomplete",
                forward=("cong",),
                attrs={
                    # Set some placeholder
                    "data-placeholder": "Search Publisher...",
                },
            )
        }

    def clean(self):
        self.cleaned_data = super(ReportForm, self).clean()
        if not self.cleaned_data["hours"]:
            self.cleaned_data["hours"] = 0
        if not self.cleaned_data["videos"]:
            self.cleaned_data["videos"] = 0
        if not self.cleaned_data["return_visits"]:
            self.cleaned_data["return_visits"] = 0
        if not self.cleaned_data["bible_studies"]:
            self.cleaned_data["bible_studies"] = 0
        if not self.cleaned_data["placements"]:
            self.cleaned_data["placements"] = 0
        return self.cleaned_data

frontend/views.py
from django.http import Http404
from django.shortcuts import render
from congregation.models import STATUS_ACTIVE, Congregation, Group, Publisher
from ministry.models import Report
from .forms import ReportForm
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dal import autocomplete
from django.contrib.auth.decorators import login_required
import calendar

DEFAULT_CONGREGATION = "wlnorth"
DEFAULT_CONG_GROUP = 3
DEFAULT_LOGIN_URL = "/admin/login/?next=/admin/"


class PublisherAutocomplete(autocomplete.Select2QuerySetView):
    def get_result_label(self, item):
        return item.name

    def get_queryset(self):
        qs = Publisher.objects.filter(status=STATUS_ACTIVE)
        if self.q:
            qs = qs.filter(
                group__congregation__code=self.forwarded.get(
                    "code", DEFAULT_CONGREGATION
                ),
                name__icontains=self.q,
            )
        return qs.order_by("name")


def get_date(year=None, month=None):
    if not year and not month:
        day_last_month = datetime.today() - relativedelta(months=1)
        year = day_last_month.year
        month = day_last_month.month
    start_date = datetime(year, month, 1)
    end_date = datetime(year, month, calendar.monthrange(year, month)[1])

    return start_date, end_date


@login_required(login_url=DEFAULT_LOGIN_URL)
def get_report(request, group_id=DEFAULT_CONG_GROUP, year=None, month=None):

    groups = set([group.name for group in request.user.groups.all()])
    group = Group.objects.get(pk=group_id)

    if group.congregation.code not in groups:
        raise PermissionError("You are not authorized to view this report")

    start_date, end_date = get_date(year=year, month=month)
    group_publishers = Publisher.objects.filter(
        group_id=group_id, status=STATUS_ACTIVE
    ).order_by("id")

    for publisher in group_publishers:
        publisher_report = Report.objects.filter(
            creation_date__gte=start_date,
            creation_date__lte=end_date,
            publisher=publisher,
        ).first()
        publisher.report = publisher_report
    return render(
        request,
        "reports.html",
        {
            "publishers": group_publishers,
            "month": calendar.month_name[end_date.month],
            "year": end_date.year,
        },
    )


def update_existing_report(form, existing_report):

    if not existing_report:
        return

    if not form:
        return

    existing_report.hours = form.cleaned_data["hours"]
    existing_report.placements = form.cleaned_data["placements"]
    existing_report.bible_studies = form.cleaned_data["bible_studies"]
    existing_report.return_visits = form.cleaned_data["return_visits"]
    existing_report.videos = form.cleaned_data["videos"]
    existing_report.remarks = form.cleaned_data["remarks"]
    existing_report.save()


def create_report(form, creation_date):
    new_report = form.save()
    if not creation_date:
        return
    new_report.creation_date = creation_date
    new_report.save()


def cong_submission(request, congregation_code=DEFAULT_CONGREGATION):
    if not Congregation.objects.filter(code=congregation_code).exists():
        raise Http404("Congregation does not exist")

    start_date, end_date = get_date()
    if not request.method == "POST":
        return render(
            request,
            "submission.html",
            {
                "form": ReportForm(),
                "congregation_code": congregation_code,
                "submission_date": f"{calendar.month_name[end_date.month]}, {end_date.year}",
            },
        )
    form = ReportForm(request.POST)

    if not form.is_valid():
        return render(request, "submission.html", {"form": form})

    selected_publisher = form.cleaned_data["publisher"]
    existing_report = Report.objects.filter(
        creation_date__gte=start_date,
        creation_date__lte=end_date,
        publisher=selected_publisher,
    ).first()

    existing_next_month_report = Report.objects.filter(
        creation_date__gt=end_date,
        publisher=selected_publisher,
    ).first()

    if "create_next_month" in request.POST:
        if existing_next_month_report:
            update_existing_report(
                form=form, existing_report=existing_next_month_report
            )
        else:
            create_report(form=form, creation_date=start_date + relativedelta(months=1))

    if "update_existing" in request.POST:
        update_existing_report(form=form, existing_report=existing_report)

    if "submit_report" in request.POST:
        if existing_report:
            return render(
                request,
                "existing.html",
                {
                    "form": form,
                    "month": calendar.month_name[end_date.month],
                    "year": end_date.year,
                },
            )
        if existing_next_month_report:
            update_existing_report(
                form=form, existing_report=existing_next_month_report
            )
        else:
            create_report(form=form, creation_date=start_date)

    return render(request, "thanks.html", {"name": selected_publisher.name})

frontend/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Just a simple field service reporting program">
    <meta name="keywords" content="HTML, CSS, JavaScript, JW.org">
    <meta name="author" content="John Eric">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'custom.bootstrap.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <title>Ministry Report</title>
  </head>
  <body class="vh-100">
    <div class="container h-100">
      <div class="row h-100">
          {% block main %}
          {% endblock %}
          {% block footer %}
          {% endblock %}
      </div>
    </div>
  </body>
</html>

frontend/templates/existing.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
<div class="col-8 mx-auto align-self-center">
    <form action="/" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div style="display: none;">
                {{ field }}
            </div>
        {% endfor %}
        <div style="text-align: center;">You have an existing report for {{month}} {{year}}</div>
        <div style="text-align: center;">
            <input type="submit" value="Update" name="update_existing" class="btn mt-2 btn-primary">
            <input type="submit" value="Submit for next month" name="create_next_month" class="btn  mt-2 btn-primary">
        </div>
    </form>
</div>
{% endblock %}

frontend/templates/reports.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<div class="col-12 mx-auto align-self-center">
    <table id="reportTable" class="table table-bordered table-hover table-responsive-md caption-top">
        <caption>{{ month }} {{ year }} Report</caption>
        <thead class="thead-light">
        <tr>
            <th scope="col" style="width:15%">Publisher</th>
            <th scope="col" style="width:10%">Hours</th>
            <th scope="col" style="width:10%">RV</th>
            <th scope="col" style="width:10%">BS</th>
            <th scope="col" style="width:10%">Placements</th>
            <th scope="col" style="width:10%">Videos</th>
            <th scope="col" style="width:25%">Remarks</th>
        </tr>
        </thead>
        <tbody>
        {% for publisher in publishers %}
            <tr>
                <th scope="row">{{ publisher.name }}</th>
                {% if publisher.report %}
                <td>{{ publisher.report.hours }}</td>
                <td>{{ publisher.report.return_visits }}</td>
                <td>{{ publisher.report.bible_studies }}</td>
                <td>{{ publisher.report.placements }}</td>
                <td>{{ publisher.report.videos }}</td>
                <td class="text-left">{{ publisher.report.remarks|linebreaks|default_if_none:"" }}</td>
                {% else %}
                    <td colspan="7">No report</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<button class="float-button" onclick="downloadReport('{{ month }}-{{ year }}', '{{ month }} {{ year }} Field Service Report');"><i class="fa fa-print"></i></button>
<script src="{% static 'jspdf.umd.min.js' %}"></script>
<script src="{% static 'jspdf.plugin.autotable.js' %}"></script>
<script src="{% static 'report.js' %}"></script>
<script src="{% static 'font-awesome/js/all.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'report.css' %}">
{% endblock %}

frontend/templates/submission.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block main %}
<div class="col-8 mx-auto align-self-center">
    <h3 class="text-center">{{ submission_date }}</h3>
    <form action="/" method="post" onreset="$('#id_publisher').val(null).trigger('change');">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="hidden" name="code" value="{{ congregation_code }}"/>
        <input type="submit" value="Submit" name="submit_report" class="btn btn-primary">
        <input type="reset" value="Reset" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block footer %}
<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete.js' %}"></script>
{{ form.media }}
<link rel="stylesheet" href="{% static 'autocomplete.css' %}">
{% endblock %}

frontend/templates/thanks.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
<div class="col-8 mx-auto align-self-center">
    <h3>Thank you {{ name }} for your submission</h3>
    <div style="text-align: center;">
        <input type="button" value="Restart" class="btn btn-primary" onclick="window.location = '/';">
    </div>
</div>
{% endblock %}